add_newline = false

[directory]
truncation_length = 1

[hostname]
ssh_only = false
format = " [$hostname]($style) "
style = "bold red"

[username]
disabled = true
show_always = true
format = "[$user@]($style)"
style_user = "bold blue"

[line_break]
disabled = true

[battery]
disabled = true

# vim:ft=dosini
